extensions:
  oauth2client:
    client_id: "${env:OIDC_CLIENT_ID}"
    client_secret: "${env:OIDC_CLIENT_SECRET}"
    token_url: "${env:OIDC_TOKEN_URL}"
    scopes: [ "observability" ]
    timeout: 10s

receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:4318
      grpc:
        endpoint: localhost:4317
  prometheus:
    config:
      scrape_configs:
        - job_name: 'litestream'
          scrape_interval: 60s
          static_configs:
            - targets: [ '0.0.0.0:9090' ]

processors:
  batch:
  attributes:
    actions:
      - key: device.serial_number
        value: "${env:DEVICE_SERIAL_NUMBER}"
        action: insert
      - key: voripos_otel_collector_version
        value: "${env:VORIPOS_OTEL_COLLECTOR_VERSION}"
        action: upsert
      - key: provisioned_environment
        value: "${env:VORIPOS_ENVIRONMENT}"
        action: upsert
      - key: bannerID
        value: "${env:VORIPOS_BANNER_ID}"
        action: upsert
      - key: bannerName
        value: "${env:VORIPOS_BANNER_NAME}"
        action: upsert
      - key: storeID
        value: "${env:VORIPOS_STORE_ID}"
        action: upsert
      - key: storeName
        value: "${env:VORIPOS_STORE_NAME}"
        action: upsert
      - key: laneID
        value: "${env:VORIPOS_LANE_ID}"
        action: upsert
      - key: laneName
        value: "${env:VORIPOS_LANE_NAME}"
        action: upsert
  memory_limiter:
    check_interval: 5s
    limit_mib: 500
    spike_limit_mib: 200

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: "${env:OTLP_HOSTNAME}:${env:OTLP_PORT}"
    auth:
      authenticator: oauth2client

service:
  extensions: [oauth2client]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter,attributes,batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp,prometheus]
      processors: [memory_limiter,attributes,batch]
      exporters: [debug, otlp]
    logs:
      receivers: [otlp]
      processors: [memory_limiter,attributes,batch]
      exporters: [debug, otlp]
